 
function hit = classify_data(x,MU,groundtruth,varargin)

n = nargin - 3;
sPr = zeros(1,n);
for k = 1:n
COV_train = varargin{k};
% prob. that x was generated by the Gaussian
% process with cov = COV_train:
p = gauss(MU, COV_train, x);
% log-likelihoods:
LL = log(p);
LL(LL<-300)=NaN;
sPr(k) = nansum(LL)/sum(~isnan(LL));
end        

[~,ML] = max(sPr); 

hit = (ML == groundtruth);

